version: "3"
services:
  app:
    image: guizo/docker-laravel:7.3
    ports:
      - 8007:80
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
  db:
    image: mysql:5.7
    ports:
      - 3007:3306
    volumes:
      - mysqldata:/var/lib/mysql
    working_dir: /home/db
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=veus-challenge
volumes:
  mysqldata:
    driver: local
